# Usa una imagen base con Python 3.7.5
FROM python:3.7.5-slim

# Configura la carpeta de trabajo
WORKDIR /app

# Copia los archivos necesarios
COPY . /app

# Instala pip actualizado
RUN pip install --upgrade pip

# Copia requirements (si lo tienes separado)
# RUN pip install -r requirements.txt

# Instala las dependencias una por una (versión exacta)
RUN pip install absl-py==0.15.0 \
    annotated-types==0.5.0 \
    anyio==3.7.1 \
    astunparse==1.6.3 \
    cached-property==1.5.2 \
    cachetools==4.2.4 \
    certifi==2025.4.26 \
    charset-normalizer==3.4.2 \
    clang==5.0 \
    click==8.1.8 \
    colorama==0.4.6 \
    customtkinter==5.0.5 \
    cycler==0.11.0 \
    darkdetect==0.8.0 \
    Deprecated==1.2.18 \
    exceptiongroup==1.3.0 \
    fastapi==0.103.2 \
    flatbuffers==1.12 \
    gast==0.4.0 \
    google-auth==1.35.0 \
    google-auth-oauthlib==0.4.6 \
    google-pasta==0.2.0 \
    grpcio==1.62.3 \
    h11==0.14.0 \
    h5py==3.1.0 \
    idna==3.10 \
    imageio==2.31.2 \
    importlib-metadata==6.7.0 \
    joblib==1.3.2 \
    keras==2.6.0 \
    Keras-Preprocessing==1.1.2 \
    kiwisolver==1.4.5 \
    Markdown==3.4.4 \
    MarkupSafe==2.1.5 \
    matplotlib==3.3.4 \
    MouseInfo==0.1.3 \
    numpy==1.19.5 \
    oauthlib==3.2.2 \
    opencv-python==4.11.0.86 \
    opt-einsum==3.3.0 \
    packaging==24.0 \
    pandas==1.1.5 \
    Pillow==8.4.0 \
    protobuf==3.19.6 \
    pyasn1==0.5.1 \
    pyasn1-modules==0.3.0 \
    PyAutoGUI==0.9.54 \
    pydantic==2.5.3 \
    pydantic_core==2.14.6 \
    PyGetWindow==0.0.9 \
    PyMsgBox==1.0.9 \
    pyparsing==3.1.4 \
    pyperclip==1.9.0 \
    PyRect==0.2.0 \
    PyScreeze==1.0.1 \
    python-dateutil==2.9.0.post0 \
    python-multipart==0.0.8 \
    pytweening==1.2.0 \
    pytz==2025.2 \
    requests==2.31.0 \
    requests-oauthlib==2.0.0 \
    rsa==4.9.1 \
    scikit-learn==0.24.2 \
    scipy==1.7.3 \
    six==1.15.0 \
    sniffio==1.3.1 \
    starlette==0.27.0 \
    tensorboard==2.6.0 \
    tensorboard-data-server==0.6.1 \
    tensorboard-plugin-wit==1.8.1 \
    tensorflow==2.6.5 \
    tensorflow-estimator==2.6.0 \
    termcolor==1.1.0 \
    tf-keras-vis==0.8.7 \
    threadpoolctl==3.1.0 \
    typing_extensions==4.7.1 \
    urllib3==2.0.7 \
    uvicorn==0.22.0 \
    Werkzeug==2.2.3 \
    wrapt==1.12.1 \
    zipp==3.15.0

# Expone el puerto donde correrá la app
EXPOSE 8000

# Comando para iniciar tu FastAPI (ajusta si tu archivo no es main.py)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
