version: '3.8'

services:
  fracture-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fracture-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
